[package]
name = "prayer_times"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
rodio = "0.17.3"
tray-icon = "0.11.3"
image = "0.25.0-preview.0"
tao = "0.26.1"